### ISSUE TITLE
Alt keys and ampersand and shortcut keys

### ISSUE THREAD

**Issue by terrameijar** [terrameijar/nd-firefox#10]
I'm not sure of the right way to phrase this but here goes:

Firefox uses shortcut keys when the menu is accessed while pressing the Alt key to reduce clicks eg: 

**P** for print
**T** for a new Tab
**Q**  for Quit

Right l'm sure you all get the picture. Right so here's the problem. In the gettext files( the .po files) we get from locamotion, the files aren't formated in such a way as to let us know what should have keyword shortcuts and what shouldn't but on mozilla.locamotion.org the words that are keyword shortcuts are clearly marked as such.

An example of this: `New Private &Window` . The _&_ makes **W** a keyword shortcut.

The only way to know if a string is meant to be formated that way is or not is to check on Locamotion, but this could be time consuming so we need to figure out a way around this.

**Comment by bhekiabstract** [comment]
Are the files not written as in the example you showed? To say they have an ampersand?

**Comment by terrameijar** [comment]
I know what the problem is now, some files still contain old code that isn't up to date...Firefox has undergone lots of changes since we started localising. So we should translate the files as they are... if there's an ampersand, put it!.

I'll close this now
